[server]
headless = true
enableCORS = true  # Enable CORS to allow cross-origin requests
enableXsrfProtection = true  # Enable XSRF protection for security
port = 80  # Port 80 is standard for HTTP; if using HTTPS, this might need to be changed

[browser]
serverAddress = "admin.mark-build.com"