[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501  # Default Streamlit port, can be changed if needed
address = "0.0.0.0"  # Listens on all network interfaces

[general]
email = "bogdansavi05@gmail.com"

[cors]
# Comma-separated list of allowed origins for CORS.
allowedOrigins = [
  "https://ic8sk8o.mark-build.com"
]